model:
    name: 'SelfSupModel'
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    test:
        dataset: ['KITTI']
        path: ['/shared/ffabi_shared_folder/datasets/original_datasets/kitti_all/sample/KITTI_tiny']
        split: ['kitti_tiny.txt']
        depth_type: ['velodyne']
save:
    depth:
        rgb: True
        viz: True
        npz: True
        png: True
