arch:
    max_epochs: 5
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 8
        dataset: ['KITTI']
        path: ['/root/packnet/kitti_raw']
        split: ['data_splits/overfit_eigen_zhou_files.txt']
        depth_type: ['velodyne']
        repeat: [10]
    validation:
        dataset: ['KITTI']
        path: ['/shared/ffabi_shared_folder/datasets/original_datasets/kitti_all/sample/KITTI_tiny']
        split: ['kitti_tiny.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/shared/ffabi_shared_folder/datasets/original_datasets/kitti_all/sample/KITTI_tiny']
        split: ['kitti_tiny.txt']
        depth_type: ['velodyne']
